# For all rules see https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md
default: false
fenced-code-language: true
no-reversed-links: true
code-fence-style:
  style: backtick
# proper-names:
#   names:
#     - SQLite
#     - VS Code
#no-bare-urls: true
no-empty-links: true
search-replace:
  rules:
    - name: prefer-https-links
      message: https links should be prefered
      searchPattern: /\[.*?\]\(http:\/\/(?!localhost).*?\)/g
    - name: custom-containers-requires-type
      searchPattern: "/(?<!<!--)::: (?!info|tip|warning|danger|details|code-group|raw)/g"
      message: custom container requires a type
