---
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
language: en-US,en-GB
dictionaryDefinitions:
  - name: project-words-internal
    path: '../project-words.txt'
    addWords: true
  - name: project-words-external
    path: './project-words.txt'
    addWords: true
dictionaries:
  - project-words-internal
  - project-words-external
  - companies
  - softwareTerms
  - misc
  - node
  - typescript
  - bash
  - html
  - css
ignorePaths:
  - 'node_modules'
  - 'project-words.txt'
  - '.github'
allowCompoundWords: true
caseSensitive: false
ignoreRegExpList:
  - code_block
  - inline_code_block
  - code-group
  - href_link
  - markdown_link
  - fragments
  - html_comment
  - heading
  - heading_ids
  - bold_text
  - italic_text
  - i_tags
  - cli_option
  - property
  - property_in_code_block
patterns:
  - name: code_block
    pattern: /`{3}[\s\S]*?`{3}/gm

  - name: inline_code_block
    pattern: /\`[-.]?[\s\S]*?(?!\w)\`/gm

  - name: html_comment
    pattern: /<!--[\s\S]*?-->/gm

  - name: markdown_link
    pattern: /-?\s*([*#]|\[.*?\])\(.*?\)/gm

  - name: heading_ids
    pattern: /\{\s*#+.+\}/

  - name: code-group
    pattern: /:{3}\scode-group[\s\S]*?:{3}/gm

  - name: href_link
    pattern: /href="[\s\S]*"/gm

  - name: fragments
    pattern: /<(Fragment|span|div)\s+(id|target)="#?.*"[\s.]*/?>/g

  - name: heading
    pattern: /^(#{1,6}.*)/

  - name: bold_text
    pattern: /\*{2}.*\*{2}|__.*__/gm

  - name: italic_text
    pattern: /\*.*\*|_.*_/gm

  - name: i_tags
    pattern: /<i>.*<\/i>/g

  - name: cli_option
    pattern: /(-[^\s]+)/g

  - name: property
    pattern: /`?`\.[a-zA-Z]*?/g

  - name: property_in_code_block
    pattern: /`(\..*)+?`/gm
